# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 05:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('question', models.CharField(max_length=50000)),
                ('duedate', models.DateField(verbose_name='due date')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=16, unique=True)),
                ('usertype', models.CharField(choices=[('Student', 'Student'), ('Teacher', 'Teacher')], default='Student', max_length=8)),
                ('password', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='homeworkId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homework.Homework'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homework.Users'),
        ),
        migrations.AddField(
            model_name='answers',
            name='homeworkId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homework.Homework'),
        ),
        migrations.AddField(
            model_name='answers',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homework.Users'),
        ),
    ]
