# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='answer',
            field=models.TextField(default=''),
        ),
    ]
