# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0002_answers_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='name',
            field=models.CharField(default='', max_length=64),
        ),
    ]
